### PR TITLE
Front end design

### PR DESCRIPTION
**Pull request by bfullam**
updated front end to comply with club design guidelines

### CODE REVIEW

**Comment by georgymh** [comment]
Verify my redesign, change anything you don't like, and before we _Merge this Pull Request_, we need to delete all the club's files (we don't need them in our repo) and link all the `.css`, `.js`, `image` files to the original URL path so that the `.html` is still visible although we are not keeping the files on our repo.

Also, let's put the `subscribe.html` inside `/demo/occprogrammingclub.html`. That way our basic front-end is not deleted once this branch is merged with _master_.

**Comment by bfullam** [comment]
I think it's done

**Comment by georgymh** [comment]
This will have to be a collaborative merge since I changed so many stuff. Please pull the trigger whenever you're ready @bfullam !

**Comment by bfullam** [comment]
Looks good, nice job!

**Pull request merged**
